### ISSUE TITLE
Download button non-functional on SeaMonkey 2.53.9

### ISSUE THREAD

**Issue by abvgdeyoj** [httptoolkit/httptoolkit.tech#10]

**Comment by pimterry** [comment]
Hi @abvgdeyoj, interesting, thanks for reporting this.

The button action is managed by JS, which automatically configures it to provide the relevant download for whatever platform you're using. The JS fails to load in Seamonkey because even the latest releases of Seamonkey don't support many modern JS features. The main one in this case being unicode matching in regexes (used for some formatting logic) which means the site JS throws a syntax error before anything runs at all. That's supported in Chrome, Firefox & Safari back since 2016, so I'd assumed it was a pretty safe bet!

I think for most users this is fine, but I see how it's problematic in some cases, so I've [added a fallback](https://github.com/httptoolkit/httptoolkit.tech/commit/21d05280924d73e7fa4b9467416e64229fbcaaae). If you click the download button now, if JS hasn't loaded or can't be run for any reason, you'll just go to https://github.com/httptoolkit/httptoolkit-desktop/releases and you can manually download the appropriate version from there. Seem reasonable? Does it now work for you?

**Comment by abvgdeyoj** [comment]
@pimterry The button now works as you described.
The arrow on the right (dropdown menu) is still non-functional, and can be made to only show up when the main button doesn't use the fallback.

**Comment by pimterry** [comment]
> The button now works as you described.

Ok, great!

> The arrow on the right (dropdown menu) is still non-functional, and can be made to only show up when the main button doesn't use the fallback.

Yes, the dropdown is JS too. That could be made to work with some fiddly CSS & hidden checkboxes, but it's complicated & a bit hacky, and I'm afraid I don't think it's worth it - the number of users (especially technical users) using browsers that don't support this is tiny (<0.05% of my visitors in the last year, according to my stats) and the dropdown at the side is just a mildly nicer UI for the download options available if you click through to https://github.com/httptoolkit/httptoolkit-desktop/releases anyway. It's slightly awkward UX, but as long as it's possible to download the app without too much trouble, I think it'll do.

I'm going to close this as fixed for now. If you do find any other show-stopping bugs in the site though, do let me know. I'm not aiming for perfect browser support, but I'd like to ensure at least all the basic functionality is widely available, in both older browsers and browsers without JS.
