### ISSUE TITLE
Cross-Origin Request Blocked on Firefox 75.0

### ISSUE THREAD

**Issue by sairam** [httptoolkit/httptoolkit.tech#5]
when accessing page https://httptoolkit.tech/pricing, I got the following error on the console. No price is being displayed.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.httptoolkit.tech/.netlify/functions/get-prices?product_ids=550380,550382,550789,550788. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
> 
> TypeError: NetworkError when attempting to fetch resource.

**Comment by pimterry** [comment]
Huh, that shouldn't happen! Thanks for reporting this. I can't reproduce it myelf though, and I'm also using Firefox 75, so something more complicated is going on.

Can you share the full response & headers you're seeing from that request? Is it coming back as a fresh response, or from your cache?

**Comment by sairam** [comment]
Its working now for some odd reason. I will do that next time I face the issue

**Comment by pimterry** [comment]
I've done some more digging, I think this is what would happen if the API _behind_ this service (the [Paddle.com](https://paddle.com) checkout API) somehow failed. I've now added explicitly error reporting for that, plus proper CORS headers so the error will be clearer in browsers: https://github.com/httptoolkit/accounts/compare/59bce2e...be52716.

Thanks again for reporting this! There's probably some rare failures there that I should handle more carefully, and I never would have noticed otherwise :smiley:.
