### ISSUE TITLE
security?

### ISSUE THREAD

**Issue by alisman** [httptoolkit/httptoolkit.tech#8]
Been looking for something like this for a long time.   But it makes me pretty nervous to install something that can intercept all http activity.  Can you reassure me somehow that this is not  incredibly dangerous?

**Comment by pimterry** [comment]
> Can you reassure me somehow that this is not incredibly dangerous?

I can, I think. First, unlike all other HTTPS debugging tools, HTTP Toolkit requires no administrator privileges, and never installs a global certificate in your OS. In fact, it makes no persistent changes to your machine at all (other than installing itself and managing its own internal configuration, like any other application).

Instead of being trusted globally by your OS and potentially capturing all HTTP on your machine, interception works by launching each targeted processes from HTTP Toolkit itself, with certificates automatically injected into that specific browser/terminal window/app only. Injection is done via a combination of environment variables, isolated browser profiles and command line switches for each target in question.

There's more information about this design here: https://httptoolkit.tech/blog/debugging-https-without-global-root-ca-certs/

In addition, the certificate authority that HTTP Toolkit uses on your machine to do this interception is generated locally & independently for each install, and the private key never leaves your machine at any point. Even whilst the launched intercepted processes are open, they don't trust anything outside your own computer.

Does that provide some confidence? I think using HTTP Toolkit has a very similar risk profile to using any other unprivileged application downloaded from the internet.

Happy to answer questions if you have specific concerns. Of course the whole project is also open source so you can peruse the details for yourself too if you'd like, or even build a custom version and run it locally to guarantee you know what code is running if you'd prefer.

**Comment by pimterry** [comment]
I'm going to close this now, but feel free to reply here if you have any more questions.

**Comment by alisman** [comment]
Thanks very much!
